In [15]:
import numpy as np

Write a NumPy program to create an array of 10 zeros.

In [16]:
zero_arr = np.zeros(10, dtype=int)
zero_arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Write a NumPy program to create an array of 10 ones.

In [17]:
ones_arr = np.ones(10, dtype=int)
ones_arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

Write a NumPy program to create a 3x3 matrix with values ranging from 0 to 8.

In [18]:
matrix3 = np.arange(9).reshape((3,3))
matrix3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Write a NumPy program to reverse an array (first element becomes the last).

In [19]:
arr = [1, 2, 3, 4, 5, 6]
print(arr)
# 1st method
print(np.flip(arr))
# 2nd method
print(arr[::-1])

[1, 2, 3, 4, 5, 6]
[6 5 4 3 2 1]
[6, 5, 4, 3, 2, 1]


Write a NumPy program to extract all odd numbers from an array.

In [20]:
odd_arr = [arr[i] for i in range(len(arr)) if arr[i] % 2 == 1]
odd_arr

[1, 3, 5]

Write a NumPy program to compute the sum of all elements, mean, and standard deviation of a given array.

In [21]:
print(np.sum(arr))
print(np.mean(arr))
print(np.std(arr))

21
3.5
1.707825127659933


Write a NumPy program to create a 5x5 matrix with random values and find the minimum and maximum values.

In [22]:
matrix5 = np.random.randint(1, 100, (5,5))
print(matrix5)
print(f"Max value: {matrix5.max()}")
print(f"Min value: {matrix5.min()}")

[[ 4 12 11 12 45]
 [29 16 58 67 37]
 [84 90 27 82 64]
 [ 9 68 18 47 76]
 [20 51  3 18 18]]
Max value: 90
Min value: 3


Write a NumPy program to create a 2D array with 1 on the border and 0 inside.

In [23]:
arr2D = np.ones([5,5], dtype=int)
print(arr2D)
print()
arr2D[1:-1, 1:-1] = 0
print(arr2D)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


Write a NumPy program to multiply two given matrices.

In [24]:
mat5 = np.random.randint(1, 100, (5,5))
print(mat5)

[[92 89 39 97  4]
 [21 27 95 52 44]
 [65 21 65 57 87]
 [21 61 92  9 95]
 [28 11 31 76 64]]


In [25]:
print(mat5 * matrix5)

[[ 368 1068  429 1164  180]
 [ 609  432 5510 3484 1628]
 [5460 1890 1755 4674 5568]
 [ 189 4148 1656  423 7220]
 [ 560  561   93 1368 1152]]


Write a NumPy program to find the unique elements of an array.

In [26]:
arr = np.array([[1, 2, 3], [1, 2, 4]])
print(arr)
print()
print(f"Uniique elements are: {np.unique(arr)}")

[[1 2 3]
 [1 2 4]]

Uniique elements are: [1 2 3 4]


Write a NumPy program to extract the elements in the odd-numbered columns of a 2D array.

In [30]:
mat2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(mat2)
for i in range(len(mat2)):
    for j in range(len(mat2[i])):
        if j % 2 != 0:
            print(mat2[i][j], end=" ")

[[1 2 3 4]
 [5 6 7 8]]
2 4 6 8 

Write a NumPy program to extract the elements in the even-numbered rows of a 2D array.

In [31]:
matrix2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(matrix2)
for i in range(len(matrix2)):
    for j in range(len(matrix2[i])):
        if j % 2 == 0:
            print(matrix2[i][j], end=" ")

[[1 2 3 4]
 [5 6 7 8]]
1 3 5 7 

Write a NumPy program to extract a subarray from a given array. The subarray should include the first 3 rows and the columns from index 1 to 4 (inclusive).

In [33]:
matrix6 = np.random.randint(1, 50, (6,6))
print(matrix6)
print()
sub_matrix6 = matrix6[:3, 1:5]
print(sub_matrix6)

[[43  7 47 12 42 10]
 [29 46  1 48 40 30]
 [10 15 43 31 26  4]
 [26 47 45 38 48  4]
 [ 9 41 45 35 47 33]
 [13  1 34 27 23  5]]

[[ 7 47 12 42]
 [46  1 48 40]
 [15 43 31 26]]


Write a NumPy program to reverse the order of elements in each column of a 2D array.

In [34]:
mat2 = np.random.randint(1, 20, (3, 5))
print(mat2)
print()
for i in range(len(mat2)):
    mat2[i] = mat2[i][::-1]
print(mat2)

[[13 16  6 13 18]
 [14 18 10 13 12]
 [17  6 15 14  6]]

[[18 13  6 16 13]
 [12 13 10 18 14]
 [ 6 14 15  6 17]]


Write a NumPy program to create a diagonal matrix from a given 1D array. The elements below the diagonal should be zero, and the elements above the diagonal should be squared.

In [38]:
arr = [1, 2, 3, 4]
matrix4 = np.zeros((4,4), dtype=int)
for i in range(len(matrix4)):
    for j in range(len(matrix4[i])):
        if i == j:
            matrix4[i][j] = arr[i]
        if j > i:
            matrix4[i][j] = arr[i] ** 2
print(matrix4)

[[1 1 1 1]
 [0 2 4 4]
 [0 0 3 9]
 [0 0 0 4]]
